Examen2/ToDoClient/ToDoClient/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
path('admin/', admin.site.urls),
path('todo/', include('todo_api_client.urls')), 
]

Examen2/ToDoClient/todo_api_client/urls.py
from django.urls import path
from . import views
from .views import (
    UserProfileListView,
    UserProfileDetailView,
    UserProfileCreateView,
    UserProfileUpdateView,
    UserProfileDeleteView,
    ToDoCreateView,
     ToDoListView,
     ToDoUpdateView,
     ToDoDeleteView,
     ToDoDetailView
)

app_name = 'todo_api_client'

urlpatterns = [
    path('profiles/', UserProfileListView.as_view(), name='userprofile_list'),
    path('profiles/<int:pk>/', UserProfileDetailView.as_view(), name='userprofile_detail'),
    path('profiles/create/', UserProfileCreateView.as_view(), name='userprofile_create'),
    path('profiles/<int:pk>/update/', UserProfileUpdateView.as_view(), name='userprofile_update'),
    path('profiles/<int:pk>/delete/', UserProfileDeleteView.as_view(), name='userprofile_delete'),


path('todos/create/', ToDoCreateView.as_view(), name='todo_create'),
path('todos/', ToDoListView.as_view(), name='list_todo'),
path('todos/<int:pk>/', ToDoDetailView.as_view(), name='todo_detail'),
path('todos/<int:pk>/update/', ToDoUpdateView.as_view(), name='todo_update'),
path('todos/<int:pk>/delete/', ToDoDeleteView.as_view(), name='todo_delete'),



    # URLs para la lista de todos los pendientes
    path('todos/ids/', views.todo_list_ids, name='todo_list_ids'),
    path('todos/ids-titles/', views.todo_list_ids_titles, name='todo_list_ids_titles'),
    path('todos/unresolved/', views.todo_list_unresolved, name='todo_list_unresolved'),
    path('todos/resolved/', views.todo_list_resolved, name='todo_list_resolved'),
    path('todos/ids-user/', views.todo_list_ids_user, name='todo_list_ids_user'),
    path('todos/resolved-user/', views.todo_list_resolved_user, name='todo_list_resolved_user'),
    path('todos/unresolved-user/', views.todo_list_unresolved_user, name='todo_list_unresolved_user'),


]

Examen2/ToDoClient/todo_api_client/models.py
from django.db import models

# Create your models here.

Examen2/ToDoClient/todo_api_client/forms.py
from django import forms

class CreateUserProfileForm(forms.Form):
    first_name = forms.CharField(max_length=255, required=False)
    last_name = forms.CharField(max_length=255, required=False)
    email = forms.EmailField()
    area = forms.CharField(max_length=255)

class UpdateUserProfileForm(forms.Form):
    first_name = forms.CharField(max_length=255, required=False)
    last_name = forms.CharField(max_length=255, required=False)
    email = forms.EmailField()
    area = forms.CharField(max_length=255)

import requests
class CreateToDoForm(forms.Form):
    task_title = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class': 'form-control'}))
    task_description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), required=False)
    assigned_user = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}))
    duration_days = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}), initial=7)
    task_priority = forms.ChoiceField(choices=[
        ("HIGH", "High"),
        ("MEDIUM", "Medium"),
        ("LOW", "Low"),
    ], widget=forms.Select(attrs={'class': 'form-control'}))
    task_status = forms.ChoiceField(choices=[
        ("NOT_STARTED", "Not Started"),
        ("IN_PROGRESS", "In Progress"),
        ("COMPLETED", "Completed"),
    ], widget=forms.Select(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super(CreateToDoForm, self).__init__(*args, **kwargs)
        # Populate the assigned_user choices with data from the API
        response = requests.get("http://127.0.0.1:8000/todo/profiles/")
        if response.status_code == 200:
            users = response.json()
            self.fields['assigned_user'].choices = [(user['id'], user['email']) for user in users]


class ToDoUpdateForm(forms.Form):
    task_title = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class': 'form-control'}))
    task_description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), required=False)
    is_completed = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}), required=False)
    assigned_user = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}))
    duration_days = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}), initial=7)
    deadline = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control'}), required=False)
    task_progress = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control'}), required=False)
    task_priority = forms.ChoiceField(choices=[
        ("HIGH", "High"),
        ("MEDIUM", "Medium"),
        ("LOW", "Low"),
    ], widget=forms.Select(attrs={'class': 'form-control'}))
    task_status = forms.ChoiceField(choices=[
        ("NOT_STARTED", "Not Started"),
        ("IN_PROGRESS", "In Progress"),
        ("COMPLETED", "Completed"),
    ], widget=forms.Select(attrs={'class': 'form-control'}))
    is_active = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}), required=False)

    def __init__(self, *args, **kwargs):
        super(ToDoUpdateForm, self).__init__(*args, **kwargs)
        # Populate the assigned_user choices with data from the API
        response = requests.get("http://127.0.0.1:8000/todo/profiles/")
        if response.status_code == 200:
            users = response.json()
            self.fields['assigned_user'].choices = [(user['id'], user['email']) for user in users]

Examen2/ToDoClient/todo_api_client/views.py
# todo_api_client/views.py

from django.shortcuts import render, redirect
from django.views.generic import TemplateView
import requests
from django.views import generic
from .forms import CreateUserProfileForm, UpdateUserProfileForm 
from django.http import JsonResponse



class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Ejemplo de solicitud GET para obtener la lista de tareas desde la API
        response = requests.get('http://localhost:8000/todo/todos/')
        if response.status_code == 200:
            tasks = response.json()
            context['tasks'] = tasks
        return context

class UserProfileListView(generic.View):
    template_name = "profile_list.html"
    context = {}
    url = "http://127.0.0.1:8000/todo/profiles/"

    def get(self, request):
        response = requests.get(self.url)
        profiles = response.json() if response.status_code == 200 else []
        self.context = {
            "profiles": profiles
        }
        return render(request, self.template_name, self.context)

class UserProfileDetailView(generic.View):
    template_name = "profile_detail.html"
    context = {}
    url = "http://127.0.0.1:8000/todo/profiles/"
    
    def get(self, request, pk):
        response = requests.get(f"{self.url}{pk}/")
        profile = response.json() if response.status_code == 200 else None
        self.context = {
            "profile": profile
        }
        return render(request, self.template_name, self.context)
    

class UserProfileCreateView(generic.View):
    template_name = "profile_create.html"
    url =  "http://127.0.0.1:8000/todo/profiles/"

    def get(self, request):
        form = CreateUserProfileForm()  # Inicializar el formulario vacío
        context = {
            "form": form
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = CreateUserProfileForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            response = requests.post(self.url, json=data)
            if response.status_code == 201:  # 201 Created
                return redirect('todo_api_client:userprofile_list')  # Redirige a la lista de GrantGoals u otra URL de éxito
            else:
                context = {
                    "form": form,
                    "error": f"Failed to create GrantGoal: {response.content.decode('utf-8')}"
                }
                return render(request, self.template_name, context, status=response.status_code)
        else:
            context = {
                "form": form,
                "error": "Invalid form data"
            }
            return render(request, self.template_name, context)


from django.shortcuts import redirect, render
from django.http import JsonResponse
from django.views import View
import requests
from .forms import UpdateUserProfileForm  # Asegúrate de importar el formulario adecuado

class UserProfileUpdateView(View):
    template_name = "profile_update.html"
    url_detail = "http://127.0.0.1:8000/todo/profiles/{pk}/"
    url_update = "http://127.0.0.1:8000/todo/profiles/{pk}/update/"

    def get(self, request, pk):
        detail_url = self.url_detail.format(pk=pk)
        response = requests.get(detail_url)
        if response.status_code == 200:
            data = response.json()
            form = UpdateUserProfileForm(initial=data)
            context = {"form": form, "profile_id": pk}
            return render(request, self.template_name, context)
        else:
            return JsonResponse({'error': 'UserProfile not found'}, status=404)

    def post(self, request, pk):
        form = UpdateUserProfileForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            update_url = self.url_update.format(pk=pk)
            response = requests.put(update_url, json=data)
            if response.status_code == 200:
                return redirect('todo_api_client:userprofile_list')
            else:
                context = {"form": form, "error": "Failed to update profile"}
                return render(request, self.template_name, context, status=response.status_code)
        else:
            context = {"form": form, "profile_id": pk}
            return render(request, self.template_name, context)

from django.shortcuts import redirect
from django.http import JsonResponse
from django.views import View  # Importa la clase View de django.views
import requests

class UserProfileDeleteView(View):
    template_name = "profile_delete.html"
    url_detail = "http://127.0.0.1:8000/todo/profiles/{pk}/"
    url_delete = "http://127.0.0.1:8000/todo/profiles/{pk}/delete/"

    def get(self, request, pk):
        detail_url = self.url_detail.format(pk=pk)
        response = requests.get(detail_url)
        if response.status_code == 200:
            data = response.json()
            context = {
                "object": data
            }
            return render(request, self.template_name, context)
        else:
            return JsonResponse({'error': 'UserProfile not found'}, status=404)

    def post(self, request, pk):
        delete_url = self.url_delete.format(pk=pk)
        response = requests.delete(delete_url)
        if response.status_code == 204:
            return redirect('todo_api_client:userprofile_list')
        else:
            return JsonResponse({'error': 'Failed to delete profile'}, status=response.status_code)
        
from .forms import CreateToDoForm

class ToDoCreateView(View):
    template_name = "todos_create.html"
    url = "http://127.0.0.1:8000/todo/todos/"

    def get(self, request):
        form = CreateToDoForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = CreateToDoForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            # Ensure 'assigned_user' is an integer (ID)
            data['assigned_user'] = int(data['assigned_user'])
            response = requests.post(self.url, json=data)
            if response.status_code == 201:
                return redirect('todo_api_client:list_todo')
            else:
                return render(request, self.template_name, {'form': form, 'error': response.content})
        return render(request, self.template_name, {'form': form})

class ToDoListView(View):
    template_name = "todos_list.html"
    url = "http://127.0.0.1:8000/todo/todos/"

    def get(self, request):
        response = requests.get(self.url)
        if response.status_code == 200:
            todos = response.json()
            return render(request, self.template_name, {'todos': todos})
        else:
            return render(request, self.template_name, {'error': 'Failed to fetch tasks'})


from django.shortcuts import render, redirect
from django.views import generic
import requests
from .forms import ToDoUpdateForm

class ToDoDetailView(generic.View):
    template_name = "detail_todo.html"
    url = "http://127.0.0.1:8000/todo/todos/"

    def get(self, request, pk):
        detail_url = f"{self.url}{pk}/"
        response = requests.get(detail_url)
        if response.status_code == 200:
            data = response.json()
            context = {"todo": data}
            return render(request, self.template_name, context)
        else:
            return render(request, 'error.html', {'error': 'ToDo not found'}, status=response.status_code)

class ToDoUpdateView(generic.View):
    template_name = "update_todo.html"
    url = "http://127.0.0.1:8000/todo/todos/"

    def get(self, request, pk):
        detail_url = f"{self.url}{pk}/"
        response = requests.get(detail_url)
        if response.status_code == 200:
            data = response.json()
            form = ToDoUpdateForm(initial=data)
            context = {
                "form": form,
                "todo_id": pk
            }
            return render(request, self.template_name, context)
        else:
            return render(request, 'error.html', {'error': 'ToDo not found'}, status=response.status_code)

    def post(self, request, pk):
        update_url = f"{self.url}{pk}/update/"
        form = ToDoUpdateForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            # Convertir el campo 'deadline' a string antes de enviar la solicitud JSON
            data['deadline'] = data['deadline'].strftime('%Y-%m-%d') if data['deadline'] else None
            response = requests.put(update_url, json=data)
            if response.status_code == 200:
                return redirect('todo_api_client:todo_detail', pk=pk)
            else:
                context = {
                    "form": form,
                    "todo_id": pk,
                    "error": "Failed to update ToDo"
                }
                return render(request, self.template_name, context, status=response.status_code)
        else:
            context = {
                "form": form,
                "todo_id": pk,
                "error": "Invalid form data"
            }
            return render(request, self.template_name, context)

class ToDoDeleteView(generic.View):
    template_name = "delete_todo.html"
    url = "http://127.0.0.1:8000/todo/todos/"

    def get(self, request, pk):
        detail_url = f"{self.url}{pk}/"
        response = requests.get(detail_url)
        if response.status_code == 200:
            data = response.json()
            context = {
                "todo": data
            }
            return render(request, self.template_name, context)
        else:
            return render(request, 'error.html', {'error': 'ToDo not found'}, status=response.status_code)

    def post(self, request, pk):
        delete_url = f"{self.url}{pk}/delete/"
        response = requests.delete(delete_url)
        if response.status_code == 204:

Examen2/ToDoClient/todo_api_client/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <div class="row">
        <div class="col">
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">CLIENT EXAM2</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'todo_api_client:userprofile_list' %}">INICIO</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    USERS
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'todo_api_client:userprofile_list' %}">List USERS</a></li>
                                    <li><a class="dropdown-item" href="{% url 'todo_api_client:userprofile_create' %}">Create Users</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    TASKS
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'todo_api_client:list_todo' %}">List Task</a></li>
                                    <li><a class="dropdown-item" href="{% url 'todo_api_client:todo_create' %}">Create Task</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'todo_api_client:todo_list_ids' %}">List Task IDs</a></li>
                                    <li><a class="dropdown-item" href="{% url 'todo_api_client:todo_list_ids_titles' %}">List Task IDs & Titles</a></li>
                                    <li><a class="dropdown-item" href="{% url 'todo_api_client:todo_list_unresolved' %}">List Unresolved Tasks</a></li>
                                    <li><a class="dropdown-item" href="{% url 'todo_api_client:todo_list_resolved' %}">List Resolved Tasks</a></li>
                                    <li><a class="dropdown-item" href="{% url 'todo_api_client:todo_list_ids_user' %}">List Task IDs & User IDs</a></li>
                                    <li><a class="dropdown-item" href="{% url 'todo_api_client:todo_list_resolved_user' %}">List Resolved Task IDs & User IDs</a></li>
                                    <li><a class="dropdown-item" href="{% url 'todo_api_client:todo_list_unresolved_user' %}">List Unresolved Task IDs & User IDs</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    TASKS_API
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="http://127.0.0.1:8000/todo/todos/ids/">List Task IDs</a></li>
                                    <li><a class="dropdown-item" href="http://127.0.0.1:8000/todo/todos/ids-titles/">List Task IDs & Titles</a></li>
                                    <li><a class="dropdown-item" href="http://127.0.0.1:8000/todo/todos/unresolved/">List Unresolved Tasks</a></li>
                                    <li><a class="dropdown-item" href="http://127.0.0.1:8000/todo/todos/resolved/">List Resolved Tasks</a></li>
                                    <li><a class="dropdown-item" href="http://127.0.0.1:8000/todo/todos/ids-user/">List Task IDs & User IDs</a></li>
                                    <li><a class="dropdown-item" href="http://127.0.0.1:8000/todo/todos/resolved-user/">List Resolved Task IDs & User IDs</a></li>
                                    <li><a class="dropdown-item" href="http://127.0.0.1:8000/todo/todos/unresolved-user/">List Unresolved Task IDs & User IDs</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            {% block left %}
            {% endblock left %}
        </div>
        <div class="col-8">
            {% block content %}
            {% endblock content %}
        </div>
        <div class="col-2"></div>
    </div>
    <div class="row">
        <div class="col"></div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.js' %}" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

Examen2/ToDoClient/todo_api_client/templates/delete_todo.html
{% extends 'base.html' %}

{% block title %}Delete Task{% endblock %}

{% block content %}
<div class="container">
    <h1 class="mt-4 mb-4">Delete Task</h1>
    <div class="card mb-4">
        <div class="card-body">
            <h5 class="card-title">{{ todo.task_title }}</h5>
            <p class="card-text">Description: {{ todo.task_description }}</p>
            <p class="card-text">Assigned to: {{ todo.assigned_user.first_name }} {{ todo.assigned_user.last_name }}</p>
            <p class="card-text">Status: {{ todo.task_status }}</p>
            <p class="card-text">Created at: {{ todo.created_at }}</p>
            <p class="card-text">Deadline: {{ todo.deadline }}</p>
            <p class="card-text">Priority: {{ todo.get_task_priority_display }}</p>
            <p class="card-text">Progress: {{ todo.task_progress }}</p>
            <p class="card-text">Active: {% if todo.is_active %} Yes {% else %} No {% endif %}</p>
        </div>
    </div>
    <p>Are you sure you want to delete this task?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete Task</button>
        <a href="{% url 'todo_api_client:todo_detail' todo.id %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

Examen2/ToDoClient/todo_api_client/templates/navbar.html
<!-- todo_api_client/templates/navbar.html -->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">Mi Proyecto</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'task-list' %}">Lista de Tareas</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

Examen2/ToDoClient/todo_api_client/templates/profile_create.html
{% extends 'base.html' %}

{% block title %}Create User Profile{% endblock title %}

{% block content %}
<h1>Create User Profile</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Create</button>
</form>
{% if error %}
<p class="text-danger">{{ error }}</p>
{% endif %}
{% endblock %}

Examen2/ToDoClient/todo_api_client/templates/profile_detail.html
{% extends 'base.html' %}

{% block title %}User Profile Detail{% endblock title %}

{% block content %}
<h1>User Profile Detail</h1>
{% if profile %}
<p>ID: {{ profile.id }}</p>
<p>Username: {{ profile.username }}</p>
<p>Email: {{ profile.email }}</p>
<p>First Name: {{ profile.first_name }}</p>
<p>Last Name: {{ profile.last_name }}</p>
<p>Area: {{ profile.area }}</p>
<a href="{% url 'todo_api_client:userprofile_update' profile.id %}" class="btn btn-secondary">Edit</a>
<a href="{% url 'todo_api_client:userprofile_delete' profile.id %}" class="btn btn-danger">Delete</a>
{% else %}
<p>Profile not found.</p>
{% endif %}
{% endblock %}

Examen2/ToDoClient/todo_api_client/templates/profile_list.html
{% extends 'base.html' %}

{% block title %}User Profiles{% endblock title %}

{% block content %}
<h1>User Profiles</h1>
<br>
<a href="{% url 'todo_api_client:userprofile_create' %}" class="btn btn-success">Create New Profile</a>
<br>
<br>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Email</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Area</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for profile in profiles %}
        <tr>
            <td>{{ profile.id }}</td>
            <td>{{ profile.email }}</td>
            <td>{{ profile.first_name }}</td>
            <td>{{ profile.last_name }}</td>
            <td>{{ profile.area }}</td>
            <td>
                <a href="{% url 'todo_api_client:userprofile_detail' profile.id %}" class="btn btn-primary">View</a>
                <a href="{% url 'todo_api_client:userprofile_update' profile.id %}" class="btn btn-secondary">Edit</a>
                <a href="{% url 'todo_api_client:userprofile_delete' profile.id %}" class="btn btn-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

Examen2/ToDoClient/todo_api_client/templates/profile_update.html
{% extends 'base.html' %}

{% block title %}Update User Profile{% endblock title %}

{% block content %}
<h1>Update User Profile</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Update</button>
</form>
{% if error %}
<p class="text-danger">{{ error }}</p>
{% endif %}
{% endblock %}

Examen2/ToDoClient/todo_api_client/templates/todos_list.html
{% extends 'base.html' %}

{% block title %}To-Do List{% endblock %}

{% block content %}
<div class="container">
    <h1 class="mt-4 mb-4">To-Do List</h1>
    <ul class="list-group mb-4">
   
        <center> <a href="{% url 'todo_api_client:todo_create' %}" class="btn btn-primary">Create New Task</a></center>
        <br>
        {% for todo in todos %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <div>
                <h5 class="mb-1">{{ todo.task_title }}</h5>
                <p class="mb-1">{{ todo.task_description }}</p>
                {% if todo.assigned_user %}
                <p class="mb-1">Assigned to: {{ todo.assigned_user.first_name }} {{ todo.assigned_user.last_name }}</p>
                {% else %}
                <p class="mb-1">Assigned to: Not assigned</p>
                {% endif %}
            </div>
            <div>
                <span class="badge bg-primary rounded-pill">{{ todo.task_status }}</span>
                <p class="mb-1">Created at: {{ todo.created_at }}</p>
                <p class="mb-1">Deadline: {{ todo.deadline }}</p>
                {% if todo.task_progress is not None %}
                <div class="progress mb-2" style="height: 20px;">
                    <div class="progress-bar" role="progressbar" style="width: {{ todo.task_progress }}%;" aria-valuenow="{{ todo.task_progress }}" aria-valuemin="0" aria-valuemax="100">
                        {{ todo.task_progress }}%
                    </div>
                </div>
                {% endif %}
                <div class="btn-group" role="group" aria-label="Task Actions">
                    <a href="{% url 'todo_api_client:todo_detail' todo.id %}" class="btn btn-info">Detail</a>
                    <a href="{% url 'todo_api_client:todo_update' todo.id %}" class="btn btn-warning">Update</a>
                    <a href="{% url 'todo_api_client:todo_delete' todo.id %}" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}